---
title: Integrated ecosystem perspectives
lightbox: TRUE
---

##  {.unnumbered}

For the purpose of synthesizing the information contained in the full suite of indicators presented in this report, we analyze the full indicator suite using multivariate methods. Principal components analysis (PCA) is a statistical method that distills a large number of potentially related indicators into a smaller number of indices representing most of the variability in the data set. We analyze the indicator suite separately by category: 1) risks to meeting management objectives, 2) management objective indicators based on fishery-independent data, 3) management objective indicators based on fishery-dependent data, and 4) other management objective indicators. A traffic light plot of the indicator suite is presented for the purpose of comprehensively viewing changes in the different parts of the ecosystem over time (@fig-traffic). A biplot of the principal components analysis is presented to convey temporal patterns in the progression of ecosystem status (figure). PCA was carried out on a scaled matrix for all indicators with at least 12 years of data; any missing values were imputed with means of the time series. In the biplot, the labels represent time (years xxxx-xxxx), the rainbow line represents chronology between adjacent years, and the distance between points conveys how different the indicator values were in those years.

